name: DateDash
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#image picker
  image_picker: ^0.8.3
#firebase
  #firebase_auth: ^3.3.6
  #cloud_firestore: ^3.1.7
  #firebase_core: ^1.6.0
  cupertino_icons: ^1.0.0
  google_fonts:
  # statem anagement
  provider: ^4.3.2+2

  # icons
  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/